###
GET http://localhost:3000/boards

### 게시글 생성 성공
POST http://localhost:3000/boards
Content-Type: application/json

{
  "title": "New Board",
  "description": "New Board Description"
}

### 게시글 생성 실패 (validation 확인)
POST http://localhost:3000/boards
Content-Type: application/json

{
  "title": "",
  "description": ""
}

###
GET http://localhost:3000/boards/1

###
DELETE http://localhost:3000/boards/1

###
PATCH http://localhost:3000/boards/1
Content-Type: application/json

{
  "status": "PRIVATE"
}